CREATE TABLE IF NOT EXISTS user_files (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    s3_location VARCHAR(255) NOT NULL,
    deleted BOOLEAN DEFAULT FALSE
);
